"""update Pokemon Model

Revision ID: 4710c9f8c0b0
Revises: d033abadf597
Create Date: 2024-01-12 12:36:33.939097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4710c9f8c0b0'
down_revision = 'd033abadf597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('pokemon_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon_type', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
